a=int(input("Enter the First number: "))
b=int(input("Enter the Second number: "))
add=(a+b)
subtract=(a-b)
multiply=(a*b)
divide=float(a/b)
print("Addition:",add)
print("Subtraction:",subtract)
print("Multiplication:",multiply)
print("Division:",divide)